# **Array reshape from csv and excel**







In [1]:
import pandas as pd
import numpy as np
csv = pd.read_csv("PP2lab.csv")
ex = pd.read_excel("PP2lab.xlsx")
arr1= np.array(csv)
arr2 = np.array(ex)

In [2]:
reshapedarr1= arr1.reshape(5,10)
print(reshapedarr1)

[[544  90 544  60 544  70 544  80 544 100]
 [545  99 545  88 545  77 545  66 545  55]
 [546  56 546  66 546  77 546  88 546  99]
 [547 100 547  89 547  78 547  67 547  54]
 [548  45 548  54 548  56 548  65 548  67]]


# **Creating Data Frame**



In [3]:
st = [[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0]]

for i in range(5):
  st[i][0] = reshapedarr1[i][0]
  for j in range(10):
    if reshapedarr1[i][j] != st[i][0]:
      st[i][j] = reshapedarr1[i][j]
std = [[elem for elem in sublst if elem != 0] for sublst in st]
cl = ['Sid','Sub1','Sub2','Sub3','Sub4','Sub5']
df = pd.DataFrame(data = std, columns = cl)
df

Sid  Sub1  Sub2  Sub3  Sub4  Sub5
0  544    90    60    70    80   100
1  545    99    88    77    66    55
2  546    56    66    77    88    99
3  547   100    89    78    67    54
4  548    45    54    56    65    67