In [ ]:
import numpy as np

class createarray:
    arr1 = np.array([10,20,30])
    print(arr1)

ob = createarray()


[10 20 30]


In [ ]:
import numpy as np
l1 = [10,20,30]
arr1 = np.array(l1)
print(arr1)

[10 20 30]


In [ ]:
import numpy as np

class nparray:
    def __init__(sd, a):
      sd.a = a
    def create(sd):
      l1 = []
      for i in range(sd.a):
          inp = int(input())
          l1.append(inp)
      arr = np.array(l1)
      print(arr)

a = int(input("Enter the no.of elements in the  array"))
ob = nparray(a)
ob.create()

Enter the no.of elements in the  array3
1
2
3
[1 2 3]


# **Single dimensional arrays**

In [ ]:
import numpy as np

arr1 = np.array([10,20,30])
l1 = [40,50,60]
arr1 = np.append(arr1, l1)
print(arr1)

[10 20 30 40 50 60]


Multi Dimensional Arrays

In [ ]:
import numpy as np
class nparray:
    def __init__(sd,arr1,arr2):
        sd.a = arr1
        sd.b = arr2
    def concat(sd):
        res = np.concatenate((sd.a, sd.b), axis=0)
        print("After Concatination")
        for i in res:
          for j in i:
            print(j, end =' ')
          print()

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,4,9],[16,25,36],[49,64,81]])
ob = nparray(arr1,arr2)
ob.concat()

After Concatination
1 2 3 
4 5 6 
7 8 9 
1 4 9 
16 25 36 
49 64 81 


# **Matrix Addition**

]






In [ ]:
import numpy as np
class nparray:
  def __init__(sd, arr1):
    sd.a = arr1
  def maddit(sd):
    for i in range(3):
      sd.a[2][i] = sd.a[0][i]+sd.a[1][i]
    print("The addition of the matrix:")
    print(sd.a[2])

arr1 = np.array([[1,2,3],[4,5,6],[0,0,0]])
ob = nparray(arr1)
ob.maddit()

The addition of the matrix:
[5 7 9]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([5,6])
arr3 = np.insert(arr1,2,arr2)
print(arr3)

[1 2 5 6 3 4]


In [ ]:
import numpy as np
class nparr:
  def __init__(sd,arr1,arr2):
    sd.a = arr1
    sd.b = arr2
  def ap(sd):
    sd.a = np.append(sd.a,sd.b)
    print(sd.a)

arr1 = np.array([1,2])
arr2 = np.array([3])
ob = nparr(arr1, arr2)
ob.ap()

[1 2 3]
