<a href="https://colab.research.google.com/github/SIDDARADA/Pandas/blob/main/pp2labd2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hstack and vstack**

In [ ]:
import numpy as np
class nparr():
  def arinit(sd):
    sd.a1 = np.array([[1,2,3],[4,5,6]])
    sd.a2 = np.array([[1,8,27],[64,125,216]])
    print("Array's Initialized")
  def arhst(sd):
    sd.hsa = np.hstack((sd.a1, sd.a2))
    print("Hstacked Array:")
    print(sd.hsa)
  def arvst(sd):
    sd.vsa = np.vstack((sd.a1, sd.a2))
    print("Vstacked Array:")
    print(sd.vsa)
ob = nparr()
ob.arinit()
ob.arhst()
ob.arvst()

Array's Initialized
Hstacked Array:
[[  1   2   3   1   8  27]
 [  4   5   6  64 125 216]]
Vstacked Array:
[[  1   2   3]
 [  4   5   6]
 [  1   8  27]
 [ 64 125 216]]


# **Array Multiplication**

In [ ]:
class nparr():
  def arrinit(sd):
    sd.a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
    sd.a2 = np.array([[1,4],[2,5]])
    print("Array's Initialized")
  def checkr(sd):
      sd.ar, sd.ac = sd.a1.shape
      sd.br, sd.bc = sd.a2.shape
      if sd.ac != sd.br:
        print("Columns and Rows are Not Matched So Adding [3,6]")
        sd.a3 = np.array([[3,6]])
        sd.a4 = np.concatenate((sd.a2, sd.a3), axis = 0)
        return sd.a4
      else:
        return  True
  def armul(sd):
    sd.b1 = sd.checkr()
    sd.c = np.array([[0,0],[0,0],[0,0]])
    if isinstance(sd.b1, bool):
      sd.ar, sd.ac = sd.a1.shape
      sd.br, sd.bc = sd.a2.shape
      for i in range(sd.ac):
        for j in range(sd.bc):
          for k in range(sd.br):
            sd.c[i][j] += sd.a1[i][k] * sd.a2[k][j]
    else:
      sd.ar, sd.ac = sd.a1.shape
      sd.br, sd.bc = sd.b1.shape
      for i in range(sd.ac):
        for j in range(sd.bc):
          for k in range(sd.br):
            sd.c[i][j] += sd.a1[i][k] * sd.b1[k][j]
    print("Matrix After Multiplication:")
    print(sd.c)
ob = nparr()
ob.arrinit()
ob.armul()

Array's Initialized
Columns and Rows are Not Matched So Adding [3,6]
Matrix After Multiplication:
[[ 14  32]
 [ 32  77]
 [ 50 122]]


# **Flip Operation**

In [ ]:
class nparr:
  def arrinit(sd):
    sd.a1 = np.array([[1,2,3],[4,5,6]])
    print("Array Initialized")
  def arflip(sd):
    sd.a2 = np.flip(sd.a1, 1)
    print(sd.a2)

ob = nparr()
ob.arrinit()
ob.arflip()

Array Initialized
[[3 2 1]
 [6 5 4]]


In [ ]:
class nparr:
  def arrinit(sd):
    sd.a1 = np.array([[1,2,3],[4,5,6]])
    print("Array Initialization")
  def mar(sd):
    sd.a2 = sd.a1 * 2
    print(sd.a2)
  def aar(sd):
    sd.a3 = sd.a1 + 2
    print(sd.a3)
  def sar(sd):
    sd.a4 = sd.a1 - 2
    print(sd.a4)

ob = nparr()
ob.arrinit()
ob.mar()
ob.aar()
ob.sar()

Array Initialization
[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]


# **Transpose of a matrix**

In [ ]:
class nparr:
  def arrinit(sd):
    sd.a1 = np.array([[1,2,3,4],[5,6,7,8]])
    print("Array Initialized")
  def at(sd):
    sd.a2 = np.transpose(sd.a1)
    print("Given Matrix is:")
    print(sd.a1)
    print("Transpose Of The Matrix is:")
    print(sd.a2)

ob = nparr()
ob.arrinit()
ob.at()

Array Initialized
Given Matrix is:
[[1 2 3 4]
 [5 6 7 8]]
Transpose Of The Matrix is:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
